const source = [
  {
    title: 'We are All in Marketing: What Evolution Tells Us About Advertising',
    speaker: 'Ethan Decker',
    lang: 'EN',
    organizer: 'IHUB',
    city: 'NY',
    videoUlr: 'https://www.youtube.com/watch?v=ZK3c9GCjSx8',
    category: 'marketing',
  },
  {
    title: 'There is No Luck. Only Good Marketing',
    speaker: 'Franz Schrepf',
    lang: 'EN',
    organizer: 'IHUB',
    city: 'Odessa',
    videoUlr: 'https://www.youtube.com/watch?v=AN-41JjIPEg',
    category: 'marketing',
  },
  {
    title: 'The greatest TED Talk ever sold',
    speaker: 'Morgan Spurlock',
    lang: 'EN',
    organizer: 'IHUB',
    city: 'Lviv',
    videoUlr: 'https://www.youtube.com/watch?v=Y2jyjfcp1as',
    category: 'PM',
  },
  {
    title: 'Start with why -- how great leaders inspire action',
    speaker: 'Simon Sinek',
    lang: 'EN',
    organizer: 'IHUB',
    city: 'Lviv',
    videoUlr: 'https://www.youtube.com/watch?v=u4ZoJKF_VuA&frags=pl%2Cwn',
    category: 'marketing',
  },
  {
    title: 'Start with why -- how great leaders inspire action',
    speaker: 'Simon Sinek',
    lang: 'EN',
    organizer: 'TED',
    city: 'Lviv',
    videoUlr: 'https://www.youtube.com/watch?v=u4ZoJKF_VuA&frags=pl%2Cwn',
    category: 'marketing',
  },
  {
    title: 'We are All in Marketing: What Evolution Tells Us About Advertising',
    speaker: 'Ethan Decker',
    lang: 'EN',
    organizer: 'IHUB',
    city: 'NY',
    videoUlr: 'https://www.youtube.com/watch?v=ZK3c9GCjSx8',
    category: 'PM',
  },
]

export default source;